import type { WidgetConfig } from "../base/types";

export const radarConfig: WidgetConfig = {
  name: "FgRadar",
  displayName: "Radar Chart",
  description: "Radar chart for multi-dimensional comparison",
  author: "yangdongnan",
  defaultStyle: { width: "100%", height: "400px" },
  defaultProps: {
    staticData: [
      { category: "Sales", value: 90 },
      { category: "Management", value: 85 },
      { category: "IT", value: 80 },
      { category: "Support", value: 70 },
      { category: "R&D", value: 95 },
      { category: "Marketing", value: 75 },
    ] as Record<string, unknown>[],
    categoryField: "category",
    valueField: "value",
    indicators: [
      { name: "Sales", max: 100 },
      { name: "Management", max: 100 },
      { name: "IT", max: 100 },
      { name: "Support", max: 100 },
      { name: "R&D", max: 100 },
      { name: "Marketing", max: 100 },
    ] as Record<string, unknown>[],
    title: "",
    showLegend: true,
    legendPosition: "bottom",
    showTooltip: true,
    showLabel: false,
    colorScheme: "default",
    customColors: [
      "#5470c6",
      "#91cc75",
      "#fac858",
      "#ee6666",
      "#73c0de",
    ] as string[],
    animation: true,
    rawOption: null as Record<string, unknown> | null,
  },
  exposedValues: [
    { key: "loading", type: "boolean", description: "Loading state" },
    { key: "chartData", type: "array", description: "Chart data" },
  ],
  configPanels: ["api", "variables", "events", "chart-linkages"],
  eventTargets: [
    {
      id: "chart-click",
      label: "Chart Click",
      description: "Triggered on chart data item click",
    },
  ],
  receivableEvents: [
    { name: "refresh", description: "Reload data" },
    {
      name: "set-data",
      description: "Set chart data",
      params: { data: "Data array" },
    },
  ],
  propertyPanel: {
    basic: ["label"],
    style: ["margin", "padding", "backgroundColor", "borderRadius"],
    props: [
      {
        key: "staticData",
        label: "Static Data",
        type: "array-editor",
        fields: [
          { key: "category", label: "Category", type: "text" },
          { key: "value", label: "Value", type: "number" },
        ],
      },
      {
        key: "categoryField",
        label: "Category Field",
        type: "text",
        placeholder: "e.g. category",
      },
      {
        key: "valueField",
        label: "Value Field",
        type: "text",
        placeholder: "e.g. value",
      },
      { key: "indicators", label: "Indicators (JSON)", type: "json" },
      { key: "title", label: "Chart Title", type: "text" },
      { key: "showLegend", label: "Show Legend", type: "switch", default: true },
      {
        key: "legendPosition",
        label: "Legend Position",
        type: "select",
        default: "bottom",
        options: [
          { label: "Top", value: "top" },
          { label: "Bottom", value: "bottom" },
          { label: "Left", value: "left" },
          { label: "Right", value: "right" },
        ],
      },
      { key: "showTooltip", label: "Show Tooltip", type: "switch", default: true },
      { key: "showLabel", label: "Show Label", type: "switch", default: false },
      { key: "animation", label: "Animation", type: "switch", default: true },
      {
        key: "colorScheme",
        label: "Color Scheme",
        type: "select",
        options: [
          { label: "Default", value: "default" },
          { label: "Dark", value: "dark" },
          { label: "Light", value: "light" },
        ],
      },
      { key: "customColors", label: "Custom Colors", type: "color-array" },
      { key: "rawOption", label: "Advanced Option (JSON)", type: "json" },
    ],
  },
};
