import type { WidgetConfig } from "../base/types";

export const filledRadarConfig: WidgetConfig = {
  name: "FgFilledRadar",
  displayName: "填充雷达图",
  type: "filled-radar",
  description: "填充雷达图, 用于多DimensionDataCompareAnalysis",
  author: "yangdongnan",
  defaultStyle: { width: "100%", height: "400px" },
  defaultProps: {
    staticData: [
      { category: "销售", value: 90 },
      { category: "管理", value: 85 },
      { category: "Info技术", value: 80 },
      { category: "客服", value: 70 },
      { category: "研发", value: 95 },
      { category: "市场", value: 75 },
    ] as Record<string, unknown>[],
    categoryField: "category",
    valueField: "value",
    indicators: [
      { name: "销售", max: 100 },
      { name: "管理", max: 100 },
      { name: "Info技术", max: 100 },
      { name: "客服", max: 100 },
      { name: "研发", max: 100 },
      { name: "市场", max: 100 },
    ] as Record<string, unknown>[],
    title: "",
    showLegend: true,
    legendPosition: "bottom",
    showTooltip: true,
    showLabel: false,
    colorScheme: "default",
    customColors: [
      "#5470c6",
      "#91cc75",
      "#fac858",
      "#ee6666",
      "#73c0de",
    ] as string[],
    fillOpacity: 0.6,
    animation: true,
    rawOption: null as Record<string, unknown> | null,
  },
  exposedValues: [
    { key: "loading", type: "boolean", description: "Loading state" },
    { key: "chartData", type: "array", description: "Chart data" },
  ],
  configPanels: ["api", "variables", "events", "chart-linkages"],
  receivableEvents: [
    { name: "refresh", description: "Reload data" },
    {
      name: "set-data",
      description: "Set chart data",
      params: { data: "Data array" },
    },
  ],
  propertyPanel: {
    basic: ["label"],
    style: ["margin", "padding", "backgroundColor", "borderRadius"],
    props: [
      {
        key: "staticData",
        label: "Static Data",
        type: "array-editor",
        fields: [
          { key: "category", label: "Category", type: "text" },
          { key: "value", label: "Value", type: "number" },
        ],
      },
      {
        key: "categoryField",
        label: "Category Field",
        type: "text",
        placeholder: "如: category",
      },
      {
        key: "valueField",
        label: "Value Field",
        type: "text",
        placeholder: "如: value",
      },
      { key: "indicators", label: "Indicators (JSON)", type: "json" },
      { key: "title", label: "Chart Title", type: "text" },
      { key: "showLegend", label: "Show Legend", type: "switch", default: true },
      { key: "showTooltip", label: "Show Tooltip", type: "switch", default: true },
      { key: "showLabel", label: "Show Label", type: "switch", default: false },
      { key: "fillOpacity", label: "填充Opacity", type: "number", default: 0.6 },
      { key: "animation", label: "Animation", type: "switch", default: true },
      {
        key: "colorScheme",
        label: "Color Scheme",
        type: "select",
        options: [
          { label: "Default", value: "default" },
          { label: "Dark", value: "dark" },
          { label: "Light", value: "light" },
        ],
      },
      { key: "customColors", label: "Custom Colors", type: "color-array" },
      { key: "rawOption", label: "Advanced Option (JSON)", type: "json" },
    ],
  },
};
