import type { WidgetConfig } from "../base/types";

export const areaChartConfig: WidgetConfig = {
  name: "FgAreaChart",
  displayName: "面积图",
  type: "area-chart",
  description: "面积图, 用于展示Data随Hrs间的变化Trend",
  author: "yangdongnan",
  defaultStyle: { width: "100%", height: "400px" },
  defaultProps: {
    staticData: [
      { category: "1month", value: 120 },
      { category: "2month", value: 200 },
      { category: "3month", value: 150 },
      { category: "4month", value: 80 },
      { category: "5month", value: 170 },
    ] as Record<string, unknown>[],
    xField: "category",
    yField: "value",
    xAxisName: "",
    yAxisName: "",
    title: "",
    showLegend: true,
    legendPosition: "bottom",
    showTooltip: true,
    showLabel: false,
    colorScheme: "default",
    customColors: [
      "#5470c6",
      "#91cc75",
      "#fac858",
      "#ee6666",
      "#73c0de",
    ] as string[],
    smooth: true,
    areaOpacity: 0.6,
    animation: true,
    rawOption: null as Record<string, unknown> | null,
  },
  exposedValues: [
    { key: "loading", type: "boolean", description: "Loading state" },
    { key: "chartData", type: "array", description: "Chart data" },
  ],
  configPanels: ["api", "variables", "events", "chart-linkages"],
  receivableEvents: [
    { name: "refresh", description: "Reload data" },
    {
      name: "set-data",
      description: "Set chart data",
      params: { data: "Data array" },
    },
  ],
  propertyPanel: {
    basic: ["label"],
    style: ["margin", "padding", "backgroundColor", "borderRadius"],
    props: [
      {
        key: "staticData",
        label: "Static Data",
        type: "array-editor",
        fields: [
          { key: "category", label: "Category", type: "text" },
          { key: "value", label: "Value", type: "number" },
        ],
      },
      {
        key: "xField",
        label: "X Axis Field",
        type: "text",
        placeholder: "如: category",
      },
      {
        key: "yField",
        label: "Y Axis Field",
        type: "text",
        placeholder: "如: value",
      },
      { key: "title", label: "Chart Title", type: "text" },
      { key: "showLegend", label: "Show Legend", type: "switch", default: true },
      { key: "showTooltip", label: "Show Tooltip", type: "switch", default: true },
      { key: "showLabel", label: "Show Label", type: "switch", default: false },
      { key: "smooth", label: "Smooth", type: "switch", default: true },
      { key: "areaOpacity", label: "RegionOpacity", type: "number", default: 0.6 },
      { key: "animation", label: "Animation", type: "switch", default: true },
      {
        key: "colorScheme",
        label: "Color Scheme",
        type: "select",
        options: [
          { label: "Default", value: "default" },
          { label: "Dark", value: "dark" },
          { label: "Light", value: "light" },
        ],
      },
      { key: "customColors", label: "Custom Colors", type: "color-array" },
      { key: "rawOption", label: "Advanced Option (JSON)", type: "json" },
    ],
  },
};
