import type { ChartWidgetMock } from '../base/widgetMock'

/** 地图 — 默认 mock（中国省份示例数据） */
export const mapChartMock: ChartWidgetMock = {
  kind: 'chart',
  staticData: [
    { name: '北京', value: 580 },
    { name: '上海', value: 720 },
    { name: '广东', value: 950 },
    { name: '浙江', value: 680 },
    { name: '江苏', value: 620 },
    { name: '山东', value: 480 },
    { name: '四川', value: 350 },
    { name: '湖北', value: 310 },
    { name: '河南', value: 280 },
    { name: '湖南', value: 260 },
    { name: '福建', value: 420 },
    { name: '安徽', value: 220 },
    { name: '河北', value: 200 },
    { name: '辽宁', value: 180 },
    { name: '陕西', value: 160 },
    { name: '重庆', value: 340 },
    { name: '天津', value: 300 },
    { name: '江西', value: 150 },
    { name: '广西', value: 130 },
    { name: '云南', value: 120 },
    { name: '贵州', value: 110 },
    { name: '吉林', value: 100 },
    { name: '黑龙江', value: 90 },
    { name: '山西', value: 140 },
    { name: '甘肃', value: 80 },
    { name: '内蒙古', value: 70 },
    { name: '新疆', value: 60 },
    { name: '海南', value: 250 },
    { name: '宁夏', value: 50 },
    { name: '青海', value: 40 },
    { name: '西藏', value: 30 },
    { name: '台湾', value: 350 },
    { name: '香港', value: 500 },
    { name: '澳门', value: 400 },
  ],
}
