import type { WidgetConfig } from "../base/types";

export const scatterChartConfig: WidgetConfig = {
  name: "FgScatterChart",
  displayName: "Scatter Chart",
  description: "散点图组件，用于展示两个变量之间的关系",
  author: "yangdongnan",
  defaultStyle: { width: "100%", height: "400px" },
  defaultProps: {
    staticData: [
      { x: 10, y: 8.04 },
      { x: 8, y: 6.95 },
      { x: 13, y: 7.58 },
      { x: 9, y: 8.81 },
      { x: 11, y: 8.33 },
      { x: 14, y: 9.96 },
      { x: 6, y: 7.24 },
      { x: 4, y: 4.26 },
      { x: 12, y: 10.84 },
      { x: 7, y: 4.82 },
      { x: 5, y: 5.68 },
    ] as Record<string, unknown>[],
    xField: "x",
    yField: "y",
    xAxisName: "",
    yAxisName: "",
    title: "",
    showLegend: true,
    legendPosition: "bottom",
    showTooltip: true,
    showLabel: false,
    colorScheme: "default",
    customColors: [
      "#5470c6",
      "#91cc75",
      "#fac858",
      "#ee6666",
      "#73c0de",
    ] as string[],
    animation: true,
    rawOption: null as Record<string, unknown> | null,
  },
  exposedValues: [
    { key: "loading", type: "boolean", description: "Loading state" },
    { key: "chartData", type: "array", description: "Chart data" },
  ],
  configPanels: ["api", "variables", "events", "chart-linkages"],
  eventTargets: [
    {
      id: "chart-click",
      label: "Chart Click",
      description: "Triggered on chart data item click",
    },
  ],
  receivableEvents: [
    { name: "refresh", description: "Reload data" },
    {
      name: "set-data",
      description: "Set chart data",
      params: { data: "Data array" },
    },
  ],
  propertyPanel: {
    basic: ["label"],
    style: ["margin", "padding", "backgroundColor", "borderRadius"],
    props: [
      {
        key: "staticData",
        label: "Static Data",
        type: "array-editor",
        fields: [
          { key: "x", label: "X Value", type: "number" },
          { key: "y", label: "Y Value", type: "number" },
        ],
      },
      { key: "xField", label: "X Axis Field", type: "text", placeholder: "如: x" },
      { key: "yField", label: "Y Axis Field", type: "text", placeholder: "如: y" },
      {
        key: "xAxisName",
        label: "X Axis Name",
        type: "text",
        placeholder: "可选",
      },
      {
        key: "yAxisName",
        label: "Y Axis Name",
        type: "text",
        placeholder: "可选",
      },
      { key: "title", label: "Chart Title", type: "text" },
      { key: "showLegend", label: "Show Legend", type: "switch", default: true },
      {
        key: "legendPosition",
        label: "Legend Position",
        type: "select",
        default: "bottom",
        options: [
          { label: "顶部", value: "top" },
          { label: "底部", value: "bottom" },
          { label: "左侧", value: "left" },
          { label: "右侧", value: "right" },
        ],
      },
      { key: "showTooltip", label: "Show Tooltip", type: "switch", default: true },
      { key: "showLabel", label: "Show Label", type: "switch", default: false },
      { key: "animation", label: "Animation", type: "switch", default: true },
      {
        key: "colorScheme",
        label: "Color Scheme",
        type: "select",
        options: [
          { label: "默认", value: "default" },
          { label: "暗色", value: "dark" },
          { label: "浅色", value: "light" },
        ],
      },
      { key: "customColors", label: "Custom Colors", type: "color-array" },
      { key: "rawOption", label: "Advanced Option (JSON)", type: "json" },
    ],
  },
};
