import type { WidgetConfig } from "../base/types";

export const bubbleChartConfig: WidgetConfig = {
  name: "FgBubbleChart",
  displayName: "气泡图",
  type: "bubble-chart",
  description: "气泡图，用于展示三个变量之间的关系",
  author: "yangdongnan",
  defaultStyle: { width: "100%", height: "400px" },
  defaultProps: {
    staticData: [
      { x: 10, y: 8.04, size: 20 },
      { x: 8, y: 6.95, size: 15 },
      { x: 13, y: 7.58, size: 25 },
      { x: 9, y: 8.81, size: 18 },
      { x: 11, y: 8.33, size: 22 },
      { x: 14, y: 9.96, size: 30 },
      { x: 6, y: 7.24, size: 12 },
      { x: 4, y: 4.26, size: 10 },
      { x: 12, y: 10.84, size: 28 },
      { x: 7, y: 4.82, size: 14 },
      { x: 5, y: 5.68, size: 16 },
    ] as Record<string, unknown>[],
    xField: "x",
    yField: "y",
    sizeField: "size",
    xAxisName: "",
    yAxisName: "",
    title: "",
    showLegend: false,
    showTooltip: true,
    showLabel: false,
    colorScheme: "default",
    customColors: [
      "#5470c6",
      "#91cc75",
      "#fac858",
      "#ee6666",
      "#73c0de",
    ] as string[],
    animation: true,
    rawOption: null as Record<string, unknown> | null,
  },
  exposedValues: [
    { key: "loading", type: "boolean", description: "Loading state" },
    { key: "chartData", type: "array", description: "Chart data" },
  ],
  configPanels: ["api", "variables", "events", "chart-linkages"],
  receivableEvents: [
    { name: "refresh", description: "Reload data" },
    {
      name: "set-data",
      description: "Set chart data",
      params: { data: "Data array" },
    },
  ],
  propertyPanel: {
    basic: ["label"],
    style: ["margin", "padding", "backgroundColor", "borderRadius"],
    props: [
      {
        key: "staticData",
        label: "Static Data",
        type: "array-editor",
        fields: [
          { key: "x", label: "X Value", type: "number" },
          { key: "y", label: "Y Value", type: "number" },
          { key: "size", label: "大小", type: "number" },
        ],
      },
      { key: "xField", label: "X Axis Field", type: "text", placeholder: "如: x" },
      { key: "yField", label: "Y Axis Field", type: "text", placeholder: "如: y" },
      {
        key: "sizeField",
        label: "大小字段",
        type: "text",
        placeholder: "如: size",
      },
      { key: "title", label: "Chart Title", type: "text" },
      { key: "showTooltip", label: "Show Tooltip", type: "switch", default: true },
      { key: "showLabel", label: "Show Label", type: "switch", default: false },
      { key: "animation", label: "Animation", type: "switch", default: true },
      {
        key: "colorScheme",
        label: "Color Scheme",
        type: "select",
        options: [
          { label: "默认", value: "default" },
          { label: "暗色", value: "dark" },
          { label: "浅色", value: "light" },
        ],
      },
      { key: "customColors", label: "Custom Colors", type: "color-array" },
      { key: "rawOption", label: "Advanced Option (JSON)", type: "json" },
    ],
  },
};
