import type { WidgetConfig } from "../base/types";
import { barChartMock } from "./mock";

export const barChartConfig: WidgetConfig = {
  name: "FgBarChart",
  displayName: "Bar Chart",
  description: "柱状图组件，支持堆叠、水平方向",
  author: "yangdongnan",
  defaultStyle: { width: "100%", height: "400px" },
  defaultProps: {
    staticData: barChartMock.staticData,
    xField: "category",
    yField: "value",
    xAxisName: "",
    yAxisName: "",
    title: "",
    showLegend: true,
    legendPosition: "bottom",
    showTooltip: true,
    showLabel: false,
    colorScheme: "default",
    customColors: [
      "#5470c6",
      "#91cc75",
      "#fac858",
      "#ee6666",
      "#73c0de",
    ] as string[],
    stack: false,
    horizontal: false,
    animation: true,
    rawOption: null as Record<string, unknown> | null,
  },
  exposedValues: [
    { key: "loading", type: "boolean", description: "Loading state" },
    { key: "chartData", type: "array", description: "Chart data" },
  ],
  configPanels: ["api", "variables", "events", "chart-linkages"],
  eventTargets: [
    {
      id: "chart-click",
      label: "Chart Click",
      description: "Triggered on chart data item click",
    },
  ],
  receivableEvents: [
    { name: "refresh", description: "Reload data" },
    {
      name: "set-data",
      description: "Set chart data",
      params: { data: "Data array" },
    },
  ],
  propertyPanel: {
    basic: ["label"],
    style: ["margin", "padding", "backgroundColor", "borderRadius"],
    props: [
      {
        key: "staticData",
        label: "Static Data",
        type: "array-editor",
        fields: [
          { key: "category", label: "Category", type: "text" },
          { key: "value", label: "Value", type: "number" },
        ],
      },
      {
        key: "xField",
        label: "X Axis Field",
        type: "text",
        placeholder: "如: category",
      },
      {
        key: "yField",
        label: "Y Axis Field",
        type: "text",
        placeholder: "如: value",
      },
      {
        key: "xAxisName",
        label: "X Axis Name",
        type: "text",
        placeholder: "可选",
      },
      {
        key: "yAxisName",
        label: "Y Axis Name",
        type: "text",
        placeholder: "可选",
      },
      { key: "title", label: "Chart Title", type: "text" },
      { key: "showLegend", label: "Show Legend", type: "switch", default: true },
      {
        key: "legendPosition",
        label: "Legend Position",
        type: "select",
        default: "bottom",
        options: [
          { label: "顶部", value: "top" },
          { label: "底部", value: "bottom" },
          { label: "左侧", value: "left" },
          { label: "右侧", value: "right" },
        ],
      },
      { key: "showTooltip", label: "Show Tooltip", type: "switch", default: true },
      { key: "showLabel", label: "Show Label", type: "switch", default: false },
      { key: "stack", label: "Stack", type: "switch", default: false },
      { key: "horizontal", label: "Horizontal", type: "switch", default: false },
      { key: "animation", label: "Animation", type: "switch", default: true },
      {
        key: "colorScheme",
        label: "Color Scheme",
        type: "select",
        options: [
          { label: "默认", value: "default" },
          { label: "暗色", value: "dark" },
          { label: "浅色", value: "light" },
        ],
      },
      { key: "customColors", label: "Custom Colors", type: "color-array" },
      { key: "rawOption", label: "Advanced Option (JSON)", type: "json" },
      {
        key: "refreshInterval",
        label: "Auto Refresh (s)",
        type: "number",
        default: 0,
        placeholder: "0=关闭",
      },
    ],
  },
};
