import type { WidgetConfig } from "../base/types";

export const stackedBarChartConfig: WidgetConfig = {
  name: "FgStackedBarChart",
  displayName: "堆叠柱状图",
  type: "stacked-bar-chart",
  description: "堆叠柱状图, 用于展示各部Min占总量的比例",
  author: "yangdongnan",
  defaultStyle: { width: "100%", height: "400px" },
  defaultProps: {
    staticData: [
      { category: "1month", value1: 120, value2: 80 },
      { category: "2month", value1: 200, value2: 120 },
      { category: "3month", value1: 150, value2: 100 },
      { category: "4month", value1: 80, value2: 60 },
      { category: "5month", value1: 170, value2: 90 },
    ] as Record<string, unknown>[],
    xField: "category",
    seriesFields: ["value1", "value2"],
    seriesNames: ["Series1", "Series2"],
    xAxisName: "",
    yAxisName: "",
    title: "",
    showLegend: true,
    legendPosition: "bottom",
    showTooltip: true,
    showLabel: false,
    colorScheme: "default",
    customColors: [
      "#5470c6",
      "#91cc75",
      "#fac858",
      "#ee6666",
      "#73c0de",
    ] as string[],
    animation: true,
    rawOption: null as Record<string, unknown> | null,
  },
  exposedValues: [
    { key: "loading", type: "boolean", description: "Loading state" },
    { key: "chartData", type: "array", description: "Chart data" },
  ],
  configPanels: ["api", "variables", "events", "chart-linkages"],
  receivableEvents: [
    { name: "refresh", description: "Reload data" },
    {
      name: "set-data",
      description: "Set chart data",
      params: { data: "Data array" },
    },
  ],
  propertyPanel: {
    basic: ["label"],
    style: ["margin", "padding", "backgroundColor", "borderRadius"],
    props: [
      {
        key: "staticData",
        label: "Static Data",
        type: "array-editor",
        fields: [
          { key: "category", label: "Category", type: "text" },
          { key: "value1", label: "Series1", type: "number" },
          { key: "value2", label: "Series2", type: "number" },
        ],
      },
      {
        key: "xField",
        label: "X Axis Field",
        type: "text",
        placeholder: "如: category",
      },
      {
        key: "seriesFields",
        label: "SeriesField (JSON)",
        type: "json",
        placeholder: '["value1", "value2"]',
      },
      {
        key: "seriesNames",
        label: "系Column name称 (JSON)",
        type: "json",
        placeholder: '["Series1", "Series2"]',
      },
      { key: "title", label: "Chart Title", type: "text" },
      { key: "showLegend", label: "Show Legend", type: "switch", default: true },
      { key: "showTooltip", label: "Show Tooltip", type: "switch", default: true },
      { key: "showLabel", label: "Show Label", type: "switch", default: false },
      { key: "animation", label: "Animation", type: "switch", default: true },
      {
        key: "colorScheme",
        label: "Color Scheme",
        type: "select",
        options: [
          { label: "Default", value: "default" },
          { label: "Dark", value: "dark" },
          { label: "Light", value: "light" },
        ],
      },
      { key: "customColors", label: "Custom Colors", type: "color-array" },
      { key: "rawOption", label: "Advanced Option (JSON)", type: "json" },
    ],
  },
};
